In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/amruthayenikonda/dirty-dataset-to-practice-data-cleaning/my_file (1).csv

# Importing the dataset

In [2]:
df=pd.read_csv('/kaggle/input/datasets/amruthayenikonda/dirty-dataset-to-practice-data-cleaning/my_file (1).csv')

In [3]:
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

Here we first check which columns have null values or any other string value.
The elimination of null value is simple as we can just do  df.dropna() in it.  but the indexed values  like 1[4] doesnot get filtered  from dropna().
The data is still dirty.

In the dataset, Peak and All Time Peak are having null and dirty values which makes the data dirty.
So in other to clean it we use the following step:

In [4]:
df.isna().sum()

Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64

From Peak, we take out the unique values which are in the Peak column.

In [5]:
df['Peak'].unique()

array(['1', '1[4]', '2[7]', '2[4]', '2[10]', nan, '1[20]', '2[c]'],
      dtype=object)

We extract the values using r'(\d+)'
r denotes raw string
\d means any digit 
+ means one or more digits
() means capture this part

In [6]:
df['Peak']=df['Peak'].str.extract(r'(\d+)')
df=df.dropna(subset=['Peak'])

Now we get a fully clean data of Peak

# For All Time Peak column

In [7]:
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1,2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2,10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2,NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [8]:
df['All Time Peak'].unique

<bound method Series.unique of 0         2
1      7[2]
2      2[5]
3     10[7]
4       NaN
5     10[9]
6       NaN
13      NaN
14      NaN
Name: All Time Peak, dtype: object>

In [9]:
df['All Time Peak']=df['All Time Peak'].str.extract(r'(\d+)')

In [10]:
df=df.dropna(subset=['All Time Peak'])
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7,"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1,2,"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2,10,"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
5,6,2,10,"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]

In [11]:
df.isna().sum()

Rank                                0
Peak                                0
All Time Peak                       0
Actual gross                        0
Adjusted gross (in 2022 dollars)    0
Artist                              0
Tour title                          0
Year(s)                             0
Shows                               0
Average gross                       0
Ref.                                0
dtype: int64

In [12]:
df['Ref.'].unique()
df['Ref.']=df['Ref.'].str.extract(r'\[(\d+)\]')

In [13]:
df=df.drop(columns='Ref.')
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571"
1,2,1,7,"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571"
2,3,1,2,"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294"
3,4,2,10,"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795"
5,6,2,10,"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709"

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 5
Data columns (total 10 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              5 non-null      int64
 1   Peak                              5 non-null      object
 2   All Time Peak                     5 non-null      object
 3   Actual gross                      5 non-null      object
 4   Adjusted gross (in 2022 dollars)  5 non-null      object
 5   Artist                            5 non-null      object
 6   Tour title                        5 non-null      object
 7   Year(s)                           5 non-null      object
 8   Shows                             5 non-null      int64
 9   Average gross                     5 non-null      object
dtypes: int64(2), object(8)
memory usage: 440.0+ bytes

In [15]:
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571"
1,2,1,7,"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571"
2,3,1,2,"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294"
3,4,2,10,"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795"
5,6,2,10,"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709"

# Finding the Hidden string of the columns 
some column name string may be hidden so we use repr(column_name) which will show its true form.

In [16]:
for col in df.columns:
    print(repr(col))

'Rank'
'Peak'
'All Time Peak'
'Actual\xa0gross'
'Adjusted\xa0gross (in 2022 dollars)'
'Artist'
'Tour title'
'Year(s)'
'Shows'
'Average gross'

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 5
Data columns (total 10 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              5 non-null      int64
 1   Peak                              5 non-null      object
 2   All Time Peak                     5 non-null      object
 3   Actual gross                      5 non-null      object
 4   Adjusted gross (in 2022 dollars)  5 non-null      object
 5   Artist                            5 non-null      object
 6   Tour title                        5 non-null      object
 7   Year(s)                           5 non-null      object
 8   Shows                             5 non-null      int64
 9   Average gross                     5 non-null      object
dtypes: int64(2), object(8)
memory usage: 440.0+ bytes

In [18]:
cols=['All Time Peak',
'Actual\xa0gross',
'Adjusted\xa0gross (in 2022 dollars)',
'Year(s)',

'Average gross']

for col in cols:
    df[col]=df[col].replace(r'[\$,]',"",regex=True).astype('int64')

ValueError: invalid literal for int() with base 10: '2023–2024'

#  Sign is removed from the data but still it is dirty as it is still not converted to int64 it is object for now.¶
So the next step is to convert it into int

In [ ]:
df

In [ ]:
df.info()